### ISSUE TITLE
[web/desktop] Some commands may not work in the Windows environment.

### ISSUE THREAD

**Issue by LI-NA** [ente-io/ente#1191]
### Description

Hi there.

I'm currently trying to develop and build ente in a Windows environment.

I've been able to successfully build mobile apps without any issues, but on the web or desktop I'm having problems due to the different environments.

First, look at the next config file on the web (`web/packages/next/next.config.base.js`), using the following command to get the git head.

```
git rev-parse --short HEAD 2>/dev/null || true
```

These commands will not work in the Windows environment, so you will need to modify them with the following commands.

```
git rev-parse --short HEAD 2> NUL || cd .
```

I came up with the following code, which I'll turn into a PR if you point me in the right direction.

```
const result = cp
        .execSync(
            "git rev-parse --short HEAD 2> " + (os.platform() === "win32" ? "NUL || cd ." : "/dev/null || true"),
            {
                cwd: __dirname,
                encoding: "utf8",
            },
        )
        .trimEnd();

// or?

try {
    const result = cp
        .execSync("git rev-parse --short HEAD", {
            cwd: __dirname,
            encoding: "utf8",
        })
        .trimEnd();

    return result;
}catch (_error) {
    return undefined;
}
```

-----------

The next problem is in the desktop. In `package.json` there are commands to delete file and create symbolic link.

```
cd ../web && yarn install && yarn build:photos && cd ../desktop && rm -f out && ln -sf ../web/apps/photos/out
```

Similarly, the rm and ln commands do not work on Windows. So I'm trying to use the [shx](https://www.npmjs.com/package/shx) package to support cross-platform like this:

```
cd ../web && yarn install && yarn build:photos && cd ../desktop && shx rm -f out && shx ln -sf ../web/apps/photos/out out
```

Since this is a new package installation, I've raised it as a issue rather than a PR. Please let me know what you think and I'll fix it.

Thanks for checking it out! I'm looking forward to the day when ente can support multiplatform in the development environment :)

### Version

main

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Windows

**Comment by mnvr** [comment]
Thank you!

For both web/desktop cases, I think the approach you're mentioning is the correct one, and since you've done the hard work figuring this out, it'll be great if you can create a PR for this too.

For the web case, I think the first option is the better one, since with the second option there will be spurious errors printed to the console. However, for readability's sake, I think we should split out the ternary into a separate variable, something like this (maybe you already had this in mind, I understand what you showed were just prototype examples):

```
    // Allow the command to fail. gitSHA will be an empty string in such cases.
    // This allows us to run the build even when we're outside of a git context.
    //
    // The /dev/null redirection is needed so that we don't print error messages
    // if someone is trying to run outside of a git context. Since the way to
    // redirect output and ignore failure is different on Windows, the command
    // needs to be OS specific.
    const command =
        os.platform() == "win32"
            ? "git rev-parse --short HEAD 2> NUL || cd ."
            : "git rev-parse --short HEAD 2>/dev/null || true";
    const result = cp
        .execSync(command, {...
```

---

For the desktop case - while I'm personally never happy adding more dependencies (though luckily in this case it's only a devDependency), I think the package you're suggesting is indeed the cleanest way in this particular scenario, so let us use that. When you add it in your PR, let us can also include a one-liner description of why this package was needed in [dependencies.md](https://github.com/ente-io/ente/blob/main/desktop/docs/dependencies.md#dx).

Also note that in general, the desktop build is not currently functional (that is, even after you do all the steps, the binary will get built but won't show a page). This is because I'm in the middle of some changes to get our app to use the contextIsolation etc features of Electron. I hope to be done soon, in a few days, just calling it out in case you reach that point and wonder why things are not working.

Cheers!

**Comment by mnvr** [comment]
Done in https://github.com/ente-io/ente/pull/1198, closing.
