### ISSUE TITLE
[cli] Failed to encrypt invalid key when adding account

### ISSUE THREAD

**Issue by vulongm** [ente-io/ente#1510]
### Description

I'm currently using ente-cli-v0.1.13-linux-amd64 on Fedora Kinoite 40 and ran into an error when trying to add an account.
```
$ ./ente account add
Enter app type (default: photos): 
Use default app type: photos
Enter export directory: /var/home/user/Photos/
Enter email address: email-here
Enter password: 
Please wait authenticating...
Enter TOTP: totp-here
2024/04/21 12:23:19 failed to encrypt invalid key
```

### Version

v0.1.13

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Linux

**Comment by Tritri1029** [comment]
Have you found a solution?

**Comment by vulongm** [comment]
I have not.

**Comment by maffinca69** [comment]
Any solutions?

**Comment by shoetten** [comment]
I have the same problem, but found a workaround. Ente saves a so called "Device Key" in your system keyring / wallet and expects it to be 32 bytes. That key somehow got corrupted in my keyring. Deleting it helped (ente-cli will create a new one if none exists) and i authorized my account successfully.

Try looking for `ente` in your system keyring (e.g. KDE Wallet or i believe GnomeKeyring / Seahorse under Gnome) and deleting the entry.

**Background**

While trying to debug the issue, i found that the underlying cause is that the key stored in my keyring is `66` bytes instead of the expected `32`. I don't know why, but it's obvious that `NewEncryptor` will [fall over with the invalid key error](https://github.com/ente-io/ente/blob/main/cli/internal/crypto/stream.go#L80) when that is the case.

Hope that helps someone with actual understanding of Go / this codebase, to fix the underlying issue.

**Comment by shoetten** [comment]
Unfortunatley, that only gets you half way there, because the next operation you execute will fail again with a similar error. Apparently what is stored in the keyring is not the same that comes out. I expect something with the `string(secret)` and `[]byte(secret)` casting being wrong. I will try to dig deeper..

**Comment by shoetten** [comment]
I made a minimal reproduction here, to better understand the issue:
https://github.com/shoetten/ente-1510-repro

One can clearly see, that what you store in the keyring in not what comes out (at least when running under Linux, i suspect the other platforms work, otherwise this issue would surly have a higher priority..)

The problem always occurs when handling characters, that are not represented by a single byte, so basically everything not ASCII. I don't know whether that's a bug in go-keyring or even deeper in the stack.

I made #3163 as a fix, although it's more of a hack, not an ideal solution.

**Comment by ua741** [comment]
Thank you @shoetten for investigation this particular issue, and providing a potential fix. 
By using your PR as an reference, we have made the required change [here](https://github.com/ente-io/ente/pull/3208). We will soon make a release for CLI with the above fix.

**Comment by ua741** [comment]
CLI v0.2.0 is out. Please let us know if you are still encountering the same issue.

**Comment by shoetten** [comment]
> CLI v0.2.0 is out. Please let us know if you are still encountering the same issue.

It's fixed for me. I think you can close this issue.

**Comment by vulongm** [comment]
Thank you, it is working here now.
