### ISSUE TITLE
Same photos and videos keep being reuploaded from the same phone

### ISSUE THREAD

**Issue by forabi** [ente-io/ente#1848]
### Description

My ente app on Android 13 keeps reuploading files that have already been uploaded. I'm self-hosting using a B2 bucket for storage. The DB, server are hosted on a local Ubuntu server using Docker Compose.

Please let me know how I can go about debugging this.

### Version

v0.8.94

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by ua741** [comment]
Usually, photos should be only re-uploaded when the hash changes. This can happen if your OS is doing some post processing at a later point of time and modifying the image metadata. Also, when you edit a particular photo using any editor.

In order to debug this, can you export your app logs and search for `re-upload` keyword. The log line will give you file localID and fileName. By searching for that localID, we might be able to find what what's happening.

PS: If you are comfortable, share the logs  at support [@] ente.io. I can also have a look.
