### ISSUE TITLE
The search doesn't work

### ISSUE THREAD

**Issue by Volzhanka63** [ente-io/ente#2053]
### Description

The search function doesn't work for me. The field is selectable, but I can't type at all. 

### Version

v.3.0.6

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by dashrandom** [comment]
Having the same issue on Windows 11. Realized it was tied to my anti virus and disabling it worked. I'm using Avast.

**Comment by Volzhanka63** [comment]
> Having the same issue on Windows 11. Realized it was tied to my anti virus and disabling it worked. I'm using Avast.

Great, thank you! I'm using stock Win Defender, just added .exe into exclusions and it worked. 
Would have never guessed that it could influence input.

**Comment by dashrandom** [comment]
Just some information for the Ente developers who might stumble upon this issue. It seems that the problem is tied to how the keyboard input field in Ente Auth is being recognized as a mail app for some reason. I discovered this by manually turning off the different protections one by one and re-enabling them and it seems the "Email client protection" function of some AVs are flagging it as a mail app from an unknown developer.

**Comment by diegoamzu** [comment]
I'm also having this issue.
