### ISSUE TITLE
Photos uploaded from web interface don't get thumbnails(all black) in the gallery view

### ISSUE THREAD

**Issue by tfoote** [ente-io/ente#2189]
### Description

I just logged in and tried things out. Uploading a number of photos to test from my desktop via the web gallery at https://web.ente.io/gallery they uploaded fine. But the thumbnails are completely black in the gallery view. 

Here's a screenshot where I've highlighted them. 
![Screenshot from 2024-06-17 20-27-01](https://github.com/ente-io/ente/assets/447804/14f2b584-687a-4738-a04b-c4fa1f99b2a6)

If I click on the pictures and view them directly they will render in full size just fine. 

I tried uploading other photos from the android app and they appear fine in the gallery alongside the black previews in the gallery. 

The photos uploaded via the website don't render on the Android app in the same way with a completely black thumbnail. It looks like this:
![signal-2024-06-17-201433_002](https://github.com/ente-io/ente/assets/447804/f3ece9d7-ade4-4b52-a25a-4477e591b4b8)

I tried doing it a second time thinking that there might have been an intermittent error on upload. But the same behavior was observed. 

The files failing to preview are JPG files from an iPhone 12 which work fine on all my other systems. 

### Version

Public website 2024-06-17

### What product are you using?

Ente Photos

### What platform are you using?

Web - Firefox

**Comment by mnvr** [comment]
Is there some extension or something that you've enabled in your Firefox? For example, Firefox has a mode where it blocks access to the canvas and so the app cannot generate thumbnails.

If that's not the case, and you can reproduce this issue in other browsers, please send your logs from the web app to support@ente.io, and thank you!

**Comment by tfoote** [comment]
This looks to be a Firefox specific issue. I don't have any intrusive extensions and I disabled the only one besides my password manager. Chromium worked fine. 

Logs sent by email.

**Comment by mnvr** [comment]
There are no errors in your logs.

I think you have enabled Firefox's "block canvas fingerprinting" setting (i.e. `privacy.resistFingerprinting` is set to true in `about:config`). That feature blocks access to the canvas, and the app can't generate thumbnails.

**Comment by mnvr** [comment]
Have also added a note about this in help - https://help.ente.io/photos/troubleshooting/thumbnails#black-thumbnails

**Comment by tfoote** [comment]
Thanks, after quite a bit of debugging to isolate it. I created a new profile and iterated to try to find the issue. And I couldn't reproduce it in the new profile. I got a popup that there was a Firefox update pending. Restarting firefox has resolved the issue. I noticed that my pdf rendering in firefox was also off while debugging. And with the restart it has been resolved too. The update queuing must have broken things. I'm on 126.0.1 (64-bit) Mozillia Firefox Snap for Ubuntu canonical-002 1.0 now I don't know where it was before, but the instance had only been running for 5 days so it wasn't that old. 

Anyway, thank you for digging into this. I'm going to close this as I can't reproduce it now, the uploads are working correctly for me now.

**Comment by mvevitsis** [comment]
I'm having the same problem when uploading videos from the Mac app. 

Since it's the app, there is no ad blocking extension.

**Comment by jonasW3F** [comment]
I'm experiencing the same issue with Brave Browser. What is a bit weird is that not all of the videos lack thumbnails. And simply re-uploading the videos with the same browser, without changing any settings, would randomly most of them correctly. Repeating this a few times will give you all correct videos in the cloud.

Deleting the videos from the cloud and re-uploading is an okay-ish workaround. But sometimes you don't have access to the exact same set of files you want to upload, which makes this very manual labor task (imagine you got a folder with many videos and you manually only uploaded a few of them, the rest you don't want. Then this strategy would actually upload the unwanted videos).

I suggest a simple UI element to ask some client to "regenerate thumbnail"

Edit: Well, I guess the better workaround is to download the files that don't have a thumbnail (but should otherwise be fine?) and re-upload them. But in any case, it would be nice to just regenerate thumbnails on demand.
