### ISSUE TITLE
The server reports an error at compile time, saying cannot use ente.FreePlanStorage (untyped int constant 5368709120) as int value in struct literal (overflows)

### ISSUE THREAD

**Issue by 709397578** [ente-io/ente#2463]
### Description

The server reports an error at compile time, saying cannot use ente.FreePlanStorage (untyped int constant 5368709120) as int value in struct literal (overflows)
![bug](https://github.com/user-attachments/assets/04eba086-3728-490b-8d4c-9225eaa3fb2d)

### What product are you using?

Ente Photos

### What platform are you using?

Server

**Comment by 709397578** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

**Comment by mnvr** [comment]
We have requested people many times not to open issues related to self hosting. It is mentioned in the issue template, in the README, and has come up many times previously in discussions. Still you chose to open an issue.

---

The compile time error you're getting is because you're trying to compile on a 32-bit machine. The server's code is compatible with 64-bit architectures only. It can be made to run on 32-bit with modifications, but there you're on your own.
