### ISSUE TITLE
Adding hidden items to hidden albums makes them visible in non-hidden areas

### ISSUE THREAD

**Issue by AntsyBoi** [ente-io/ente#2895]
### Description

Device: Pixel 7 on GrapheneOS version 2024082200 (latest stable branch release)

# Steps to reproduce:
1. Hide items
2. Add those hidden items to a new hidden album from the "Hidden" menu
3. Exit the hidden menu and view the albums section on the search page
4. All hidden albums will be visible along with the regular albums

This bug also allows you to view the insides of "Hidden albums" from the albums menu without authenticating. You can also view the hidden albums and their thumbnail image by going into the add item to album button when selecting a non-hidden item.

## A theoretical fix/feature to solve this issue:
Add a hidden albums menu only visible within the hidden menu. This would solve this bug while also adding categorization to the hidden items.

### Version

v0.9.27

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by ashilkn** [comment]
I think I've understood what the issue is. When you create a new album from the Hidden section, we do not currently make it hidden by default. I do see that it should be hidden by default. 

So just to make sure I've understood your issue correctly, does hiding the album (from the options on the top right) right after creating it from the hidden section resolve your issue?

**Comment by AntsyBoi** [comment]
Yes, I didn't realize that you could manually hide albums like that. I thought it was only through the hidden menu. Making the albums hidden by default when creating them from the hidden menu fixes my issue. Thank you!
