### ISSUE TITLE
[Auth][Mobile] Not possible to close FAQ on iOS on swipe down when one category is open

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2909]
### Description

1. Open Ente Auth on IPhone 15
2. Tap on 3 lines
3. Tap on Support
4. Tap on FAQ
5. Swipe down to close this window is possible
6. Tap on FAQ
7. Open first option How secure is Auth?
8. Try to swipe down to close this window not possible.

https://github.com/user-attachments/assets/b4135f4f-94b2-49f3-9fdf-22d1f253d271

### Version

3.1.3

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS

**Comment by vishnukvmd** [comment]
You can close the bottom sheet by clicking outside.

**Comment by TomsDex** [comment]
I understand if this has been flagged as a "won't fix" but from just Vishnu's comment there was no indication of that. I've been able to replicate this today on Android and the issue lies in the fact that when no category is open you're able to swipe to close the FAQ page but this ability is removed when one category is open. Flagging it as a "won't fix" means inconsistent navigation, as for it to be consistent, swipe down to close should also be removed when no category is open.

https://github.com/user-attachments/assets/7161e745-b57f-4b0d-9834-63f83fba2c8f
