### ISSUE TITLE
Back gesture on android closes the app

### ISSUE THREAD

**Issue by r-vdp** [ente-io/ente#3524]
Often when viewing a picture full screen, the back gesture closes the app instead of going back to the previous screen, which is very annoying. The only way to actually go back, is to click the little arrow in the upper right hand corner.

This doesn't happen all the time, but it does fairly regularly.

I run the latest version of ente from the play store, 0.9.46, on a pixel 9 running grapheneos (android 14).

**Comment by harrrrshit** [comment]
Agreed, here are some examples where this will happen.

1) If i click on hamburger menu at the top left corner from the home tab, it loads the menu. And after that when I click the back button it closes the app and launches the home screen instead of taking me back to home tab. 

2) - Go to Search tab, Search Something, Don't press Enter, Instead press back button to cancel Search, You will see keyboard is down now which is the right thing to do, Now Press back button again, Boom the same problem instead of showing the search tab again, it closes the app. (If You will press enter still the same thing will happen)

3) - Go to Search tab, Search Something, Go to any search results Now press back button. You will see you are taken back to search results page which again is the right thing to do, Now Press back button again, Boom the same problem instead of showing the search tab again, this time for a change it takes you to the home tab and not the home screen. Its like I am pressing back button twice.

4) - Go to Albums page, Open any Album, click the Cast option at the top right corner. Now press back button to close the popup. You will see that cast popup is closed which again is the right thing to do, However now press button again, you will think it will close the album and will take you back to albums page, But no it again closes the app instead of doing that. 

5) I found that after Deleting all my trash, if I press back button it closes the app instead of actually going back.. 

6) Open any photo, Click on three dots in above right corner, Click on 'set as', Dont click on anything now, click back, Now again press back, Now Pressing back at this point closes the app instead of going back to previous screen that is the photos album.
