### ISSUE TITLE
Export stopped working

### ISSUE THREAD

**Issue by ph00lt0** [ente-io/ente#661]
I noticed that newly created albums in the last weeks have not been exported, unlike the others. 
Continuous sync is still enabled, and last export time is today, yet quite some pictures are missing. 

I tried to resolve it by setting the export folder again, but it now shows, the total number of my pictures under Pending items for quite some hours already, nothing much seems to be happening. How should I go about fixing this? It seems quite mad to export it all from scratch, if that would help at all.

**Comment by mnvr** [comment]
For my own reference, I'll also summarize the status here:
- The best guess we had was that the `export_status.json` was getting corrupted in some way (multiple clients running or some other threading issue)
- However, that file just doesn't seem to exist, so maybe the problem is something else (maybe we're not able to write the export_status for some reason).

**Comment by mnvr** [comment]
Is there is something in the logs (Help > View logs) when you press "Resync"?

**Comment by mnvr** [comment]
Ha, nice! At least now we know what's going wrong.

> Besides that would be good if the app can show useful errors / solution to resolve this.

Agreed! This really isn't meant to be happening, but at the least the app should've given some generic error instead of silently doing nothing on resync.

> The location is granted tho in the security panel of preferences. Wonder what I could change the permissions of the file itself to. Any suggestions?

Ente might not have access to the directory in which you've kept the "ente Photos" folder (I assume that's where you're trying to export to). That is, from the example path that you've shown, it seems that the "ente Photos" folder is in your home directory, so in this case it'll need access to the home directory in System settings > Privacy & Security > Files and Folders.

If you don't want to give ente access to the entire home directory, you can kill the desktop app, move the entire folder to another location (say Documents or Downloads), give access to that area, and then restart your export, selecting the new location.

**Comment by mnvr** [comment]
> What you describe here is exactly what I tried to explain in my previous response that I already assesed that ente does have granted access to this location.

It is not easy for me to debug this remotely. I understand that you've tried many of these steps already, but (a) my current belief is that it is some permissions issue on your local machine, and (b) I'm not sure what to suggest more. It is always possible there is a bug though, so I'll continue to think more, if something clicks.

**Comment by mnvr** [comment]
> can you tell me what read/write permissions should be on the file location for which users? I can try to modify that. But I need to know what it should be like.

`-rw-r--r--` for the current user should be fine

<img width="252" alt="Screenshot 2024-03-05 at 13 24 19" src="https://github.com/ente-io/ente/assets/24503581/0083ac5d-46e2-459e-a9ae-6fc252624a0b">

My feeling is that it is not the file permissions per se, but some of the macOS Security and Privacy restrictions that are getting in the way. One scenario I can imagine is that the Ente app that you've authorized in your system settings is different from the Ente app that you're running (as in, both of them are Ente only, maybe even the same version, but they were in different places so maybe the OS is treating them differently) - to rule this out, you can right click on the entry for ente in the "Files and Folders" privacy setting, and use "Show in Finder).

But yes, let's try with file permissions too! 📿 Maybe making it read/write for all to give it a shot too.

**Comment by mnvr** [comment]
Haha, nice! Just happy that this got solved :) 

Thanks for debugging this!
