### ISSUE TITLE
Binary "ente-cli-v0.1.11-windows-amd64.zip" detected as virus/trojan

### ISSUE THREAD

**Issue by BumbleJackFlash** [ente-io/ente#727]
### Description

Binary "ente-cli-v0.1.11-windows-amd64.zip" with hash "562E4D75DF5C830F570952846558F255FDCFF949D66E2FA2EA3B88FC158ED7CC" was flagged as trojan on 06MAR24 around ~2233 GMT by:
- Microsoft Defender - Trojan:Win32/Wacatac.B!ml
- VirusTotal (MaxSecure) - Trojan.Malware.300983.susgen

Curious what explanation is.

### What platform are you using?

Desktop - Windows

**Comment by ua741** [comment]
> Curious what explanation is.

From a cursory search, this seems like a common false positive in the go binary:

 - https://go.dev/doc/faq#virus
 - https://github.com/lian/msfs2020-go/issues/14
 - https://groups.google.com/g/golang-nuts/c/Au1FbtTZzbk

--

@BumbleJackFlash, we recently made a minor change in our build process. Can you please confirm if the antivirus flags the older version? https://github.com/ente-io/cli/releases/tag/v0.1.10

**Comment by mnvr** [comment]
This is likely because we recently changed how we build the go binaries.

Previously, we used **goreleaser** ([this is the workflow](https://github.com/ente-io/cli/blob/main/.github/workflows/release.yml#L30))

Now, we use **go-release-action** ([this is the workflow](https://github.com/ente-io/ente/blob/main/.github/workflows/cli-release.yml#L41)).

If you can help us find why this is not being flagged, that'll be great! Thank you for helping.

**Comment by mnvr** [comment]
So I've gone ahead and taken a look at it, and I cannot spot anything amiss.

When looking carefully though, I noticed there was one difference in the build configuration from earlier to now. Earlier, we were setting `CGO_ENABLED=0` in the goreleaser config, but in the migration to the new go-release-action, this flag was not set. The default is CGO_ENABLED=1, which might explain some of the differences in the binaries.

If now modified our workflows (and also the release.sh script that can be used to build the cli binaries locally). I've also created a new pre-release - you can try these new binaries at https://github.com/ente-io/ente/releases/tag/cli-v0.1.12-test.

If that is still giving you alerts, then you can try building the binaries locally on your machine

```
git clone https://github.com/ente-io/ente
cd ente/cli
./release.sh
```

Then you'll find the binaries in the bin folder.

If even that is giving you alerts, I can't see anything wrong and I think your virus scanner is just giving you false positives.

I'll close this for now, but please reopen if you can help us find the exact issue that's triggering the virus scanner.

---

ps. Thanks for reporting this! Because when investigating this another thing @ua741 found was to pass `-ldflags="-s -w"  -trimpath` to further reduce the size of the generated binaries. And indeed, the binaries you'll see in the pre-release are almost half the size, so something good came out of this exercise 😊

**Comment by BumbleJackFlash** [comment]
ente-cli-v0.1.12-test-windows-amd64.zip with hash 09FF6FEBED62D662D2040252A65F3751DA2B20DC32CD0AC2394B1EE54EA06CCA
Isn't flagged by Microsoft Defender.  Looking forward to when this makes it to Release.

**Comment by mnvr** [comment]
Awesome! Thanks for checking and letting us know. For now, please continue using this v0.1.12-test - there are some other improvements we have planned for CLI that we want to make soon, once they're done we'll make a new release.

Thanks again.
